"""Ensure generated convention docs match check_conventions.py."""

from __future__ import annotations

import importlib.util
import re
import subprocess
import sys
from pathlib import Path

SCAFFOLD_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(SCAFFOLD_ROOT / "scripts"))

from sync_conventions import render_bugbot_section, render_rule_section  # noqa: E402

SYNC_SCRIPT = SCAFFOLD_ROOT / "scripts" / "sync_conventions.py"
CHECKER_PATH = SCAFFOLD_ROOT / "template" / "scripts" / "check_conventions.py"
RULES_PATH = SCAFFOLD_ROOT / ".cursor" / "rules" / "langchain-conventions.mdc"
BUGBOT_PATH = SCAFFOLD_ROOT / ".cursor" / "BUGBOT.md"

BEGIN_MARKER = "<!-- banned-apis:begin (generated by scripts/sync_conventions.py) -->"
END_MARKER = "<!-- banned-apis:end -->"


def _load_checker():
    spec = importlib.util.spec_from_file_location("check_conventions", CHECKER_PATH)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load checker from {CHECKER_PATH}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _extract_marked_section(content: str) -> str:
    pattern = re.compile(
        re.escape(BEGIN_MARKER) + r"\n(.*?)\n" + re.escape(END_MARKER),
        re.DOTALL,
    )
    match = pattern.search(content)
    assert match is not None, "Missing banned-apis marker pair"
    return match.group(1)


def test_rules_banned_section_matches_checker():
    checker = _load_checker()
    expected = render_rule_section(checker.BANNED_APIS)
    actual = _extract_marked_section(RULES_PATH.read_text(encoding="utf-8"))
    assert actual == expected


def test_bugbot_banned_section_matches_checker():
    checker = _load_checker()
    expected = render_bugbot_section(checker.BANNED_APIS)
    actual = _extract_marked_section(BUGBOT_PATH.read_text(encoding="utf-8"))
    assert actual == expected


def test_sync_conventions_check_passes():
    result = subprocess.run(
        [sys.executable, str(SYNC_SCRIPT), "--check"],
        cwd=SCAFFOLD_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, result.stderr or result.stdout
