#!/usr/bin/env python3
"""Generate banned-API sections in Cursor docs from check_conventions.py."""

from __future__ import annotations

import argparse
import importlib.util
import re
import sys
from pathlib import Path

SCAFFOLD_ROOT = Path(__file__).resolve().parent.parent
CHECKER_PATH = SCAFFOLD_ROOT / "template" / "scripts" / "check_conventions.py"
RULES_PATH = SCAFFOLD_ROOT / ".cursor" / "rules" / "langchain-conventions.mdc"
BUGBOT_PATH = SCAFFOLD_ROOT / ".cursor" / "BUGBOT.md"

BEGIN_MARKER = "<!-- banned-apis:begin (generated by scripts/sync_conventions.py) -->"
END_MARKER = "<!-- banned-apis:end -->"


def load_checker():
    spec = importlib.util.spec_from_file_location("check_conventions", CHECKER_PATH)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load checker from {CHECKER_PATH}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def render_rule_section(banned_apis) -> str:
    broken = [api for api in banned_apis if api.category == "broken-import"]
    deprecated = [api for api in banned_apis if api.category == "deprecated"]

    lines = ["### Broken imports (removed in v0.3+)"]
    for api in broken:
        for bullet in api.rule_bullets:
            lines.append(f"- {bullet}")

    lines.append("")
    lines.append("### Deprecated shim — do not use for new code")
    for api in deprecated:
        for bullet in api.rule_bullets:
            lines.append(f"- {bullet}")

    return "\n".join(lines)


def render_bugbot_section(banned_apis) -> str:
    lines = []
    for api in banned_apis:
        lines.append(f"- [ ] {api.bugbot_item}")
    return "\n".join(lines)


def splice_marked_section(content: str, generated: str) -> str:
    pattern = re.compile(
        re.escape(BEGIN_MARKER) + r"\n.*?\n" + re.escape(END_MARKER),
        re.DOTALL,
    )
    replacement = f"{BEGIN_MARKER}\n{generated}\n{END_MARKER}"
    if not pattern.search(content):
        raise ValueError(f"Missing marker pair:\n{BEGIN_MARKER}\n...\n{END_MARKER}")
    return pattern.sub(replacement, content, count=1)


def sync_file(path: Path, generated: str) -> tuple[str, bool]:
    original = path.read_text(encoding="utf-8")
    updated = splice_marked_section(original, generated)
    changed = updated != original
    return updated, changed


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Sync banned-API docs from template/scripts/check_conventions.py."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if generated sections are stale (no writes).",
    )
    args = parser.parse_args(argv)

    checker = load_checker()
    rule_section = render_rule_section(checker.BANNED_APIS)
    bugbot_section = render_bugbot_section(checker.BANNED_APIS)

    targets = (
        (RULES_PATH, rule_section, "langchain-conventions.mdc"),
        (BUGBOT_PATH, bugbot_section, "BUGBOT.md"),
    )

    stale: list[str] = []
    for path, generated, label in targets:
        updated, changed = sync_file(path, generated)
        if args.check:
            if changed:
                stale.append(label)
        elif changed:
            path.write_text(updated, encoding="utf-8")
            print(f"Updated {path.relative_to(SCAFFOLD_ROOT)}")

    if stale:
        print(
            "Stale generated sections (run: python scripts/sync_conventions.py):\n"
            + "\n".join(f"  - {name}" for name in stale),
            file=sys.stderr,
        )
        return 1

    if not args.check:
        print("Convention docs are in sync.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
